# Generated by Django 3.2.13 on 2022-06-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.CharField(choices=[('ND', 'Noodles'), ('RE', 'Rice'), ('UD', 'Not sure')], default='UD', max_length=2),
        ),
    ]
