# Generated by Django 3.2.13 on 2022-06-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.ImageField(default=None, upload_to='food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_link',
            field=models.URLField(default=None),
        ),
    ]
