# Generated by Django 3.2.13 on 2022-06-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220610_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.ImageField(blank=True, upload_to='food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_link',
            field=models.URLField(blank=True),
        ),
    ]
